"""drop_geo_catalogs

Revision ID: 00ba028d973d
Revises: e2f3a4b5c6d7
Create Date: 2026-07-19 18:18:25.904330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00ba028d973d'
down_revision: Union[str, Sequence[str], None] = 'e2f3a4b5c6d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.drop_constraint('instituciones_municipio_id_fkey', 'instituciones', type_='foreignkey')
    op.drop_column('instituciones', 'municipio_id')
    op.drop_table('municipios')
    op.drop_table('departamentos')
    op.drop_table('paises')
    op.drop_constraint('uq_usuarios_cedula', 'usuarios', type_='unique')
    op.drop_index('ix_usuarios_cedula', table_name='usuarios')
    op.create_index('ix_usuarios_cedula', 'usuarios', ['cedula'], unique=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_cedula'), table_name='usuarios')
    op.create_index(op.f('ix_usuarios_cedula'), 'usuarios', ['cedula'], unique=False)
    op.create_unique_constraint(op.f('uq_usuarios_cedula'), 'usuarios', ['cedula'], postgresql_nulls_not_distinct=False)
    op.add_column('instituciones', sa.Column('municipio_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('instituciones_municipio_id_fkey'), 'instituciones', 'municipios', ['municipio_id'], ['id'])
    op.create_table('municipios',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('departamento_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['departamento_id'], ['departamentos.id'], name=op.f('municipios_departamento_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('municipios_pkey'))
    )
    op.create_table('departamentos',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('pais_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['pais_id'], ['paises.id'], name=op.f('departamentos_pais_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('departamentos_pkey'))
    )
    op.create_table('paises',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('codigo', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('paises_pkey')),
    sa.UniqueConstraint('codigo', name=op.f('paises_codigo_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('nombre', name=op.f('paises_nombre_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
