"""add reset token to usuarios

Revision ID: 09a2301938e2
Revises: 13e0027db1e9
Create Date: 2026-06-18 15:41:31.164972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09a2301938e2'
down_revision: Union[str, Sequence[str], None] = '13e0027db1e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('reset_token', sa.String(length=255), nullable=True))
    op.add_column('usuarios', sa.Column('reset_token_expira', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_usuarios_reset_token'), 'usuarios', ['reset_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_reset_token'), table_name='usuarios')
    op.drop_column('usuarios', 'reset_token_expira')
    op.drop_column('usuarios', 'reset_token')
    # ### end Alembic commands ###
