"""add catalogos geograficos

Revision ID: 38b9156a4961
Revises: c4c36348f794
Create Date: 2026-06-09 19:38:39.832254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38b9156a4961'
down_revision: Union[str, Sequence[str], None] = 'c4c36348f794'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paises',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('departamentos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('pais_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['pais_id'], ['paises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('municipios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('departamento_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['departamento_id'], ['departamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('municipios')
    op.drop_table('departamentos')
    op.drop_table('paises')
    # ### end Alembic commands ###
