"""datos_contacto_solicitud

Revision ID: 4a0464fddfc9
Revises: 8d6f33335e90
Create Date: 2026-06-14 14:05:06.279373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a0464fddfc9'
down_revision: Union[str, Sequence[str], None] = '8d6f33335e90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solicitudes', sa.Column('cedula', sa.String(length=20), nullable=True))
    op.add_column('solicitudes', sa.Column('telefono', sa.String(length=20), nullable=True))
    op.add_column('solicitudes', sa.Column('correo_contacto', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solicitudes', 'correo_contacto')
    op.drop_column('solicitudes', 'telefono')
    op.drop_column('solicitudes', 'cedula')
    # ### end Alembic commands ###
