"""update academico fields

Revision ID: 53351e9ca14b
Revises: 52fdbf95e437
Create Date: 2026-06-09 20:04:37.785410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53351e9ca14b'
down_revision: Union[str, Sequence[str], None] = '52fdbf95e437'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instituciones', sa.Column('codigo_ies', sa.String(length=20), nullable=True))
    op.add_column('instituciones', sa.Column('tipo', sa.String(length=50), nullable=True))
    op.add_column('programas', sa.Column('codigo_snies', sa.String(length=20), nullable=True))
    op.add_column('programas', sa.Column('tipo_formacion', sa.String(length=50), nullable=True))
    op.add_column('programas', sa.Column('metodologia', sa.String(length=50), nullable=True))
    op.add_column('programas', sa.Column('institucion_id', sa.UUID(), nullable=False))
    op.alter_column('programas', 'facultad_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'programas', 'instituciones', ['institucion_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'programas', type_='foreignkey')
    op.alter_column('programas', 'facultad_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('programas', 'institucion_id')
    op.drop_column('programas', 'metodologia')
    op.drop_column('programas', 'tipo_formacion')
    op.drop_column('programas', 'codigo_snies')
    op.drop_column('instituciones', 'tipo')
    op.drop_column('instituciones', 'codigo_ies')
    # ### end Alembic commands ###
