"""add homologacion asignatura fields

Revision ID: 8d6f33335e90
Revises: e983d3d3da43
Create Date: 2026-06-09 20:25:32.385471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d6f33335e90'
down_revision: Union[str, Sequence[str], None] = 'e983d3d3da43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('homologacion_asignaturas', sa.Column('calificacion_origen', sa.Float(), nullable=True))
    op.add_column('homologacion_asignaturas', sa.Column('codigo_destino', sa.String(length=20), nullable=True))
    op.add_column('homologacion_asignaturas', sa.Column('semestre_destino', sa.String(length=10), nullable=True))
    op.add_column('homologacion_asignaturas', sa.Column('intensidad_horaria_destino', sa.Float(), nullable=True))
    op.add_column('homologacion_asignaturas', sa.Column('tipo_destino', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('homologacion_asignaturas', 'tipo_destino')
    op.drop_column('homologacion_asignaturas', 'intensidad_horaria_destino')
    op.drop_column('homologacion_asignaturas', 'semestre_destino')
    op.drop_column('homologacion_asignaturas', 'codigo_destino')
    op.drop_column('homologacion_asignaturas', 'calificacion_origen')
    # ### end Alembic commands ###
