"""semestre_destino int

Revision ID: c6d0741549a5
Revises: 9593501dcfad
Create Date: 2026-06-16 19:45:04.371033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6d0741549a5'
down_revision: Union[str, Sequence[str], None] = '9593501dcfad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('homologacion_asignaturas', 'semestre_destino',
        existing_type=sa.VARCHAR(length=10),
        type_=sa.Integer(),
        existing_nullable=True,
        postgresql_using='semestre_destino::integer'  # <-- agrega esto
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('homologacion_asignaturas', 'semestre_destino',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    # ### end Alembic commands ###
