"""add programa ids to solicitudes

Revision ID: e983d3d3da43
Revises: 53351e9ca14b
Create Date: 2026-06-09 20:12:05.799391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e983d3d3da43'
down_revision: Union[str, Sequence[str], None] = '53351e9ca14b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solicitudes', sa.Column('programa_origen_id', sa.UUID(), nullable=True))
    op.add_column('solicitudes', sa.Column('programa_destino_id', sa.UUID(), nullable=True))
    op.alter_column('solicitudes', 'institucion_origen',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('solicitudes', 'programa_origen',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('solicitudes', 'institucion_destino',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('solicitudes', 'programa_destino',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_foreign_key(None, 'solicitudes', 'programas', ['programa_destino_id'], ['id'])
    op.create_foreign_key(None, 'solicitudes', 'programas', ['programa_origen_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'solicitudes', type_='foreignkey')
    op.drop_constraint(None, 'solicitudes', type_='foreignkey')
    op.alter_column('solicitudes', 'programa_destino',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('solicitudes', 'institucion_destino',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('solicitudes', 'programa_origen',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('solicitudes', 'institucion_origen',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('solicitudes', 'programa_destino_id')
    op.drop_column('solicitudes', 'programa_origen_id')
    # ### end Alembic commands ###
